apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-django-deploy
spec: 
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: react-django-container
        image: tahmid55/react-django-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000